--- scripts/dtc/include-prefixes/arm64/rockchip/Makefile	2017-08-30 04:32:30.000000000 -0400
+++ scripts/dtc/include-prefixes/arm64/rockchip/Makefile	2017-09-03 16:56:17.000000000 -0400
@@ -5,6 +5,7 @@
 dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3368-px5-evb.dtb
 dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3368-r88.dtb
 dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-evb.dtb
+dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-firefly.dtb
 dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-gru-kevin.dtb
 
 always		:= $(dtb-y)
