#!/bin/sh
case $1/$2 in
  pre/*)
    systemctl stop NetworkManager.service
    #echo 1 > /sys/bus/pci/devices/0000\:02\:00.0/reset
    #echo 0 > "/sys/bus/pci/devices/0000:02:00.0/d3cold_allowed" # nvme
    #echo 0 > "/sys/bus/pci/devices/0000:03:00.0/d3cold_allowed" # wifi
    rmmod intel_ipts
    rmmod mei_me
    rmmod mei
    rmmod mwifiex_pcie
    rmmod mwifiex
    ;;
  post/*)
    modprobe intel_ipts
    modprobe mei_me
    modprobe mei
    modprobe mwifiex_pcie
    modprobe mwifiex
    #echo 1 > /sys/bus/pci/devices/0000\:02\:00.0/reset
    echo 1 > /sys/bus/pci/rescan
    systemctl start NetworkManager.service
    ;;
esac
