--- scripts/dtc/include-prefixes/arm64/socionext/Makefile	2017-08-30 04:32:30.000000000 -0400
+++ scripts/dtc/include-prefixes/arm64/socionext/Makefile	2017-09-03 16:56:17.000000000 -0400
@@ -1,5 +1,7 @@
 dtb-$(CONFIG_ARCH_UNIPHIER) += \
+	uniphier-ld11-global.dtb \
 	uniphier-ld11-ref.dtb \
+	uniphier-ld20-global.dtb \
 	uniphier-ld20-ref.dtb
 
 always		:= $(dtb-y)
